# Web Scrape NBA Game Data

In [1]:
# Import dependencies
import pandas as pd
from webdriver_manager.chrome import ChromeDriverManager
from selenium import webdriver
from selenium.webdriver.support.ui import Select
from selenium.webdriver.common.by import By
import time

In [2]:
# Create a Web Driver Object
driver = webdriver.Chrome(ChromeDriverManager().install())

====== WebDriver manager ======
Could not get version for google-chrome with the command:  powershell "$ErrorActionPreference='silentlycontinue' ; (Get-Item -Path "$env:PROGRAMFILES\Google\Chrome\Application\chrome.exe").VersionInfo.FileVersion ; if (-not $? -or $? -match $error) { (Get-Item -Path "$env:PROGRAMFILES(x86)\Google\Chrome\Application\chrome.exe").VersionInfo.FileVersion } if (-not $? -or $? -match $error) { (Get-Item -Path "$env:LOCALAPPDATA\Google\Chrome\Application\chrome.exe").VersionInfo.FileVersion } if (-not $? -or $? -match $error) { reg query "HKCU\SOFTWARE\Google\Chrome\BLBeacon" /v version } if (-not $? -or $? -match $error) { reg query "HKLM\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Google Chrome" /v version }"
Current google-chrome version is UNKNOWN
Get LATEST chromedriver version for UNKNOWN google-chrome
Trying to download new driver from https://chromedriver.storage.googleapis.com/110.0.5481.77/chromedriver_win32.zip
Driver has been saved in cache [C:\Users\emera\.wdm\drivers\chromedriver\win32\110.0.5481.77]
<ipython-input-2-83694e59ee80>:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(ChromeDriverManager().install())

## Pull Regular Season Data

In [39]:
# Connect to the website
driver.get(url="https://www.nba.com/stats/teams/boxscores/?Season=2021-22&SeasonType=Regular%20Season")

In [40]:
# Select the drop down element that allows user to choose which page to view
table_section = driver.find_element(By.CLASS_NAME, "Crom_base__f0niE")
sel = Select(table_section.find_element(By.CLASS_NAME, "DropDown_select__4pIg9"))

In [41]:
# Select the "ALL" option, which is Index 0
sel.select_by_visible_text("All")
# sel.select_by_index(0)

In [42]:
# Read the game stats table on the webpage
time.sleep(1) # In case the table takes a while to load
stats = driver.find_element(By.CLASS_NAME, "Crom_table__p1iZz").get_attribute('outerHTML')

In [43]:
# Convert the table (list) into a DataFrame
result = pd.read_html(stats)

In [44]:
# Pull the table into a DataFrame
table_df = result[0]
table_df

,Team,Match Up,Game Date,W/L,MIN,PTS,FGM,FGA,FG%,3PM,...,FT%,OREB,DREB,REB,AST,STL,BLK,TOV,PF,+/-
0,BOS,BOS @ MEM,04/09/2022,W,240,139,54,99,54.5,18,...,100.0,14,42,56,34,5,2,15,20,29
1,CLE,CLE vs. MIL,04/09/2022,W,240,133,51,94,54.3,19,...,70.6,10,38,48,39,5,5,12,26,18
2,MIL,MIL @ CLE,04/09/2022,L,240,115,39,88,44.3,12,...,78.1,8,33,41,27,7,2,12,14,-18
3,ATL,ATL @ HOU,04/09/2022,W,240,130,45,87,51.7,21,...,79.2,13,37,50,29,4,4,13,19,16
4,WAS,WAS @ CHA,04/09/2022,L,240,108,42,94,44.7,8,...,61.5,17,26,43,25,12,3,11,16,-16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2455,HOU,HOU @ MIN,10/19/2021,L,240,106,40,88,45.5,11,...,68.2,12,29,41,21,13,3,24,25,-18
2456,LAL,LAL vs. GSW,10/18/2021,L,240,114,45,95,47.4,15,...,47.4,5,40,45,21,7,4,18,25,-7
2457,GSW,GSW @ LAL,10/18/2021,W,240,121,41,93,44.1,14,...,83.3,9,41,50,30,9,2,17,18,7
2458,MIL,MIL vs. BKN,10/18/2021,W,240,127,48,105,45.7,17,...,77.8,13,41,54,25,8,9,8,19,23
2459,BKN,BKN @ MIL,10/18/2021,L,240,104,37,84,44.0,17,...,56.5,5,39,44,19,3,9,13,17,-23

In [45]:
# Drop unnecessary columns
table_df = table_df.drop(['Match Up', 'Game Date', 'W/L', 'FG%', '3P%', 'FT%'], axis=1)

In [46]:
# Rename the columns to match the database schema
table_df = table_df.rename(columns={"Team":"team"})
table_df = table_df.rename(columns={"MIN":"min", "PTS":"pts", "FGM":"fgm"})
table_df = table_df.rename(columns={"FGA":"fga", "3PM":"threepm", "3PA":"threepa", "FTM":"ftm", "FTA":"fta"})
table_df = table_df.rename(columns={"OREB":"oreb", "DREB":"dreb", "REB":"reb", "AST":"ast", "STL":"stl"})
table_df = table_df.rename(columns={"BLK":"blk", "TOV":"tov", "PF":"pf", "+/-":"point_diff"})

In [47]:
# Export the dataframe into a CSV file
table_df.to_csv("Data/Scraped/NBA_Data_Reg_Season_2022.csv")

## Pull Play-In Data

In [48]:
# Connect to the website
driver.get(url="https://www.nba.com/stats/teams/boxscores/?Season=2021-22&SeasonType=PlayIn")

In [49]:
# Read the table on the webpage
time.sleep(1) # In case the table takes a while to load
stats = driver.find_element(By.CLASS_NAME, "Crom_table__p1iZz").get_attribute('outerHTML')

In [50]:
# Convert the table (list) into a DataFrame
result = pd.read_html(stats)

In [51]:
# Pull the table into a DataFrame
table_df = result[0]
table_df

,Team,Match Up,Game Date,W/L,MIN,PTS,FGM,FGA,FG%,3PM,...,FT%,OREB,DREB,REB,AST,STL,BLK,TOV,PF,+/-
0,ATL,ATL @ CLE,04/14/2022,W,240,107,39,80,48.8,9,...,90.9,10,32,42,15,5,3,13,19,6
1,CLE,CLE vs. ATL,04/14/2022,L,240,101,37,81,45.7,13,...,82.4,8,28,36,23,8,4,14,20,-6
2,LAC,LAC vs. NOP,04/14/2022,L,240,101,35,85,41.2,9,...,64.7,12,33,45,20,7,3,8,21,-4
3,NOP,NOP @ LAC,04/14/2022,W,240,105,43,88,48.9,6,...,52.0,17,37,54,20,2,3,9,26,4
4,SAS,SAS @ NOP,04/12/2022,L,240,103,37,91,40.7,13,...,72.7,8,26,34,19,4,3,6,20,-10
5,NOP,NOP vs. SAS,04/12/2022,W,240,113,44,81,54.3,8,...,73.9,8,45,53,25,4,7,14,22,10
6,ATL,ATL vs. CHA,04/12/2022,W,240,132,49,94,52.1,16,...,72.0,12,42,54,31,5,6,12,25,29
7,CHA,CHA @ ATL,04/12/2022,L,240,103,34,90,37.8,13,...,75.9,11,30,41,22,4,4,14,24,-29
8,LAC,LAC @ MIN,04/11/2022,L,240,104,34,78,43.6,16,...,74.1,7,32,39,19,5,5,17,28,-5
9,MIN,MIN vs. LAC,04/11/2022,W,240,109,36,83,43.4,14,...,62.2,12,37,49,19,10,2,13,26,5
10,BKN,BKN vs. CLE,04/11/2022,W,240,115,45,84,53.6,9,...,66.7,10,33,43,33,9,9,14,20,7
11,CLE,CLE @ BKN,04/11/2022,L,240,108,41,92,44.6,9,...,85.0,10,30,40,26,9,2,15,21,-7

In [52]:
# Drop unnecessary columns
table_df = table_df.drop(['Match Up', 'Game Date', 'W/L', 'FG%', '3P%', 'FT%'], axis=1)

In [53]:
# Rename the columns to match the database schema
table_df = table_df.rename(columns={"Team":"team"})
table_df = table_df.rename(columns={"MIN":"min", "PTS":"pts", "FGM":"fgm"})
table_df = table_df.rename(columns={"FGA":"fga", "3PM":"threepm", "3PA":"threepa", "FTM":"ftm", "FTA":"fta"})
table_df = table_df.rename(columns={"OREB":"oreb", "DREB":"dreb", "REB":"reb", "AST":"ast", "STL":"stl"})
table_df = table_df.rename(columns={"BLK":"blk", "TOV":"tov", "PF":"pf", "+/-":"point_diff"})

In [54]:
# Export the dataframe into a csv file
table_df.to_csv("Data/Scraped/NBA_Data_Play_In_2022.csv")

## Pull Playoff Data

In [56]:
# Connect to the website
driver.get(url="https://www.nba.com/stats/teams/boxscores/?Season=2021-22&SeasonType=Playoffs")

In [57]:
# Select the drop down element that allows user to choose which page to view
table_section = driver.find_element(By.CLASS_NAME, "Crom_base__f0niE")
sel = Select(table_section.find_element(By.CLASS_NAME, "DropDown_select__4pIg9"))

In [58]:
# Select the "ALL" option, which is Index 0
sel.select_by_visible_text("All")
# sel.select_by_index(0)

In [59]:
# Read the table on the webpage
time.sleep(1) # In case the table takes a while to load
stats = driver.find_element(By.CLASS_NAME, "Crom_table__p1iZz").get_attribute('outerHTML')

In [60]:
# Convert the table (list) into a DataFrame
result = pd.read_html(stats)

In [61]:
# Pull the table into a DataFrame
table_df = result[0]
table_df

,Team,Match Up,Game Date,W/L,MIN,PTS,FGM,FGA,FG%,3PM,...,FT%,OREB,DREB,REB,AST,STL,BLK,TOV,PF,+/-
0,BOS,BOS vs. GSW,06/15/2022,L,240,90,34,80,42.5,11,...,91.7,11,30,41,27,8,8,23,16,-13
1,GSW,GSW @ BOS,06/15/2022,W,240,103,38,92,41.3,19,...,100.0,15,29,44,27,13,7,17,20,13
2,BOS,BOS @ GSW,06/12/2022,L,240,94,31,75,41.3,11,...,67.7,8,39,47,18,2,2,18,16,-10
3,GSW,GSW vs. BOS,06/12/2022,W,240,104,41,88,46.6,9,...,86.7,4,35,39,23,9,2,7,28,10
4,BOS,BOS vs. GSW,06/09/2022,L,240,97,34,85,40.0,15,...,73.7,11,31,42,22,8,6,16,17,-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
169,TOR,TOR @ PHI,04/15/2022,L,240,111,40,82,48.8,12,...,82.6,7,28,35,27,1,8,8,26,-20
170,GSW,GSW vs. DEN,04/15/2022,W,240,123,43,82,52.4,16,...,72.4,10,31,41,33,5,8,13,22,16
171,DEN,DEN @ GSW,04/15/2022,L,240,107,43,93,46.2,11,...,76.9,9,26,35,26,8,3,11,22,-16
172,MEM,MEM vs. MIN,04/15/2022,L,240,117,39,86,45.3,7,...,74.4,8,27,35,25,7,8,12,24,-13
173,MIN,MIN @ MEM,04/15/2022,W,240,130,45,90,50.0,16,...,88.9,11,35,46,32,5,7,19,32,13

In [62]:
# Drop unnecessary columns
table_df = table_df.drop(['Match Up', 'Game Date', 'W/L', 'FG%', '3P%', 'FT%'], axis=1)

In [63]:
# Rename the columns to match the database schema
table_df = table_df.rename(columns={"Team":"team"})
table_df = table_df.rename(columns={"MIN":"min", "PTS":"pts", "FGM":"fgm"})
table_df = table_df.rename(columns={"FGA":"fga", "3PM":"threepm", "3PA":"threepa", "FTM":"ftm", "FTA":"fta"})
table_df = table_df.rename(columns={"OREB":"oreb", "DREB":"dreb", "REB":"reb", "AST":"ast", "STL":"stl"})
table_df = table_df.rename(columns={"BLK":"blk", "TOV":"tov", "PF":"pf", "+/-":"point_diff"})

In [65]:
# Export the dataframe into a csv file
table_df.to_csv("Data/Scraped/NBA_Data_Playoffs_2022.csv")

In [68]:
# Close the web browser
driver.quit()